'use strict';

const TRACKER_DTO_CONTRACT_VERSION = '1.0.0';
const TRACKER_SETTINGS_CONTRACT_VERSION = '1.0.0';

module.exports = {
  TRACKER_DTO_CONTRACT_VERSION,
  TRACKER_SETTINGS_CONTRACT_VERSION,
};
